### Ejercicio 1::
#### Para el Sistema Lineal:
$$\left\{\begin{align}
6x_1 & = 12\\
6x_2+3x_1 & = -12\\
7x_3-2x_2+4x_1 & = 14\\
21x_4+9x_3-3x_2+5x_1 & = -2
\end{align}\right.$$

#### Encuentre los valores de $x_1, x_2, x_3, x_4$ utilizando sustitución progresiva. Encuentre la descomposición LU del sistema anterior. Qué puede concluir ####

#### Despejamos $X_1$ en la primera ecuación ####
$$\begin{align}
x_1 & =\frac{12}{2} && \mbox{entonces}\ & x_1=2
\end{align}$$

#### Encontramos $x_2$  con el valor de $x_1$
$$\begin{align}
x_2 & =\frac{-12-3(2)}{6} && \mbox{entonces}\ & x_1=-3
\end{align}$$

#### Una vez definidos los valores de $x_1$  y $x_2$ encontramos el valor de $x_3$
$$\begin{align}
x_3 & =\frac{14-4(2)+2(-3)}{7} && \mbox{entonces}\ & x_3=0
\end{align}$$

#### Conociendo los valores de $x_1$ , $x_2$ y $x_3$ hallamos el valor de $x_4$
$$\begin{align}
x_3 & =\frac{-2-5(2)+3(-3)-9(0)}{21} && \mbox{entonces}\ & x_4=-1
\end{align}$$
#### Forma Matricial $Ax=b$

$$\left(\begin{array}{cccc}6 & 0 & 0 & 0 \\ 3 & 6 & 0 & 0 \\ 4 & -2 & 7 & 0 \\ 5 & -3 & 9 & 21 \end{array}\right)
\left(\begin{array}{c} x_1 \\ x_2 \\ x_3 \\ x_4 \end{array}\right)=
\left(\begin{array}{c} 12 \\ -12 \\ 14 \\ -2 \end{array}\right)$$


### Programa ###

In [8]:
import numpy as np
### Matriz del Sistema:
A=np.array([[6,0,0,0],[3,6,0,0],[4,-2,7,0],[5,-3,9,21]])

### Términos Independientes:
b= np.array([12,-12,14,-2])

### Número de Ecuaciones:
n= np.size(b) 

### Vector para guardar información
x= np.zeros(n)

### Sustitución Progresiva:
for i in range (n):
    sumj=0
    for j in range (i):
        sumj+=A[i,j]*x[j]
    x[i]=(b[i]-sumj)*1/A[i,i]
print (x)  
        


[ 2. -3.  0. -1.]


#### Matriz $L=LU$

$$\left(\begin{array}{cccc}6 & 0 & 0 & 0 \\ 3 & 6 & 0 & 0 \\ 4 & -2 & 7 & 0 \\ 5 & -3 & 9 & 21 \end{array}\right)
\left(\begin{array}{cccc}1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 1 \end{array}\right)$$


### Conclusión ###
#### La descomposición de matrices LU es muy útil ya que permite alivianar la cantidad de operaciones al momento de resolver un sistema  extenso pues su proceso es más abreviado optimizando el tiempo a la hora de programar. ####

### Ejercicio 2 

#### Resolver las siguientes matrices mediante la descomposición de Cholesky
$$A=\left(\begin{array}{ccc} 4&6&10\\6&25&19\\10&19&62 \end{array}\right)$$
$$B=\left(\begin{array}{ccc} 4&6&10\\6&3&19\\10&19&62 \end{array}\right)$$

#### Analizar el caso y escribir sus conclusiones.
#### 1. Verificar si A es simétrica y definida positiva
#### Simétrica: $A=A^{T}$
$$\left(\begin{array}{ccc} 4&6&10\\6&25&19\\10&19&62 \end{array}\right)=\left(\begin{array}{ccc} 4&6&10\\6&25&
19\\10&19&62 \end{array}\right)$$
#### Calculamos los determinantes de las sub-matrices principales de A
#### Menor principal 1:
$$A_1=\left|\begin{array}{c} 4 \end{array}\right|= 4 > 0$$
#### Menor principal 2:
$$A_2=\left|\begin{array}{cc} 4&6\\6&25 \end{array}\right|=100-36 = 64 > 0 $$
#### Menor principal 3:
$$A_3=\left|\begin{array}{ccc} 4&6&10\\6&25&19\\10&19&62 \end{array}\right|=4756-1092-1360=2304 > 0 $$
#### Debido a que la matriz A es simétrica y definida positiva utilizamos la descomposición de Cholesky
#### Donde: $[U]=[L]^{T}$
$$A=LU=LL^{T}$$
#### Es decir:
$$\left(\begin{array}{ccc} 4&6&10\\6&25&19\\10&19&62 \end{array}\right)=
\left(\begin{array}{ccc} l_{11}&0&0\\l_{21}&l_{22}&0\\l_{31}&l_{32}&l_{33} \end{array}\right)
\left(\begin{array}{ccc} l_{11}&l_{21}&l_{31}\\0&l_{22}&l_{32}\\0&0&l_{33} \end{array}\right)$$
#### Realizamos el producto:
$$\left(\begin{array}{ccc} 4&6&10\\6&25&19\\10&19&62 \end{array}\right)=\left(\begin{array}{ccc} l_{11}^{2}&l_{11}
l_{21}&l_{11}l_{31}\\l_{11}l_{21}&l_{21}^{2}+l_{22}^{2}&l_{21}l_{31}+l_{22}l_{32}\\l_{11}l_{31}&l_{31}l_{21}+l_{32}
l_{22}&l_{31}^{2}+l_{32}^{2}+l_{33}^{2} \end{array}\right)$$
#### Igualamos elemento a elemento

#### Fila 1::
$$\begin{align}l_{11}^{2}=4 && \mbox{entonces}\ &&
l_{11}=2\end{align}$$
$$\begin{align}l_{11}l_{21}=6 && \mbox{entonces}\ && l_{21}=3\end{align}$$
$$\begin{align}l_{11}l_{31}=10 && \mbox{entonces}\ && l_{31}=5\end{align}$$

#### Fila 2::
$$\begin{align}l_{21}^{2}l_{22}^{2}=25 && \mbox{entonces}\ && l_{22}=4\end{align}$$
$$\begin{align}l_{21}l_{31}+l_{22}l_{32}=19 && \mbox{entonces}\ && l_{32}=1\end{align}$$

#### Fila 3::
$$\begin{align}l_{31}^{2}+l_{32}^{2}+l_{33}^{2}=62 && \mbox{entonces}\ && l_{33}=6\end{align}$$

#### La matriz $L$ es:
$$L=\left(\begin{array}{ccc} 2&0&0\\3&4&0\\5&1&6 \end{array}\right)$$

#### Descomposicion Cholesky:
$$\left(\begin{array}{ccc} 4&6&10\\6&25&19\\10&19&62 \end{array}\right)=
\left(\begin{array}{ccc} 2&0&0\\3&4&0\\5&1&6 \end{array}\right)
\left(\begin{array}{ccc} 2&3&5\\0&4&1\\0&0&6 \end{array}\right)$$

#### Programa ####

In [24]:
import numpy as np
def cholesky(A):
    A=np.array(A,float)
    L=np.zeros_like(A)
    n,_=np.shape(A)
    for j in range (n):
        for i in range(j,n):
            if i==j:
                L[i,j]=np.sqrt(A[i,j]-np.sum(L[i,:j]**2))
            else:
                L[i,j]=(A[i,j]-np.sum(L[i,:j]*L[j,:j]))/L[j,j]
    return L
A=[[4,6,10],[6,25,19],[10,19,62]]
l=cholesky(A)
print(l,'\n')
print(l,'L \n')
print(l.T,'L^T \n')
print(np.dot(l,l.T),'LL^T \n')
B=[[4,6,10],[6,3,19],[10,19,62]]
l=cholesky(B)
print(l,'L \n')
print(l.T,'L^T \n')
print(np.dot(l,l.T),'LL^T' )


[[2. 0. 0.]
 [3. 4. 0.]
 [5. 1. 6.]] 

[[2. 0. 0.]
 [3. 4. 0.]
 [5. 1. 6.]] L 

[[2. 3. 5.]
 [0. 4. 1.]
 [0. 0. 6.]] L^T 

[[ 4.  6. 10.]
 [ 6. 25. 19.]
 [10. 19. 62.]] LL^T 

[[ 2.  0.  0.]
 [ 3. nan  0.]
 [ 5. nan nan]] L 

[[ 2.  3.  5.]
 [ 0. nan nan]
 [ 0.  0. nan]] L^T 

[[ 4. nan nan]
 [nan nan nan]
 [nan nan nan]] LL^T


<ipython-input-24-98506aec0c2a>:9: RuntimeWarning: invalid value encountered in sqrt
  L[i,j]=np.sqrt(A[i,j]-np.sum(L[i,:j]**2))


### Conclusión ###
#### Cholesky al ser un método directo permitió agilizar las operaciones pues la devolución de resultados fue eficiente, pero se puede observar que es aplicable para un sistema de ecuaciones limitado pues pudimos comprobar que es simétrico, es definida positiva pudiendo ser descompuesta como el producto de una matriz triangular inferior y su traspuesta como podemos observar en el programa. ####

#### 3. Utilice el metodo de Jacobi, Gauss-Seidel y SOR (w=1.1) para resolver el sisguietne sistema lineas con una precision de cuatro cifras decimales
$$\left(\begin{array}{cccc} 7 & 1 &-1 & 2 \\1 & 8 & 0 &-2 \\ 2 &-2 &-1 & 6 \end{array}\right)
\left(\begin{array}{c} x_1 \\ x_2 \\ x_3 \\ x_4 \end{array}\right)=
\left(\begin{array}{c} 3 \\ -5 \\ 4 \\ -3 \end{array}\right)$$
#### Compare el numero de iteraciones necesario en cada algoritmo. Analice el error cometido si la solucion exacta es $x=(1,-1,1,-1)^T$

### Metodo Jacobi ###
$$\left(\begin{array}{cccc} 7 & 1 &-1 & 2 \\1 & 8 & 0 &-2 \\ 2 &-2 &-1 & 6 \end{array}\right)
\left(\begin{array}{c} x_1 \\ x_2 \\ x_3 \\ x_4 \end{array}\right)=
\left(\begin{array}{c} 3 \\ -5 \\ 4 \\ -3 \end{array}\right)$$

### Vector Inicial $ x^{(o)}$::
$$x^{(o)}= \left(\begin{array}{cccc} 0 & 0 & 0 & 0 \end{array}\right)$$

### Formula::
$$x^{k}=D^{-1}(L+U)x^{(k-1)}+D^{-1}b$$

### Entonces
 |Matriz Diagonal |Matriz Triangular Inferior| Matriz Triangular Superior |
  |:--- |:---- |:----:|
  |$$D=\left(\begin{array}{cccc} 7 & 0 & 0 & 0 \\0 & 8 & 0 & 0\\ 0 & 0 & 4 & 0 \\ 0 & 0 & 0 & 6 \end{array}\right)$$|$$L=\left(\begin{array}{cccc} 0 & 0 & 0 & 0 \\-1 & 0 & 0 & 0\\ 1 & 0 & 0 & 0 \\ -2 & 2 & 1 & 0\end{array}\right)$$| $$U=\left(\begin{array}{cccc} 0 & 1 & 1 & -2 \\0 & 0 & 0 & 2\\ 0 & 0 & 0 & 1 \\ 0 & 0 & 0 & 0\end{array}\right)$$

### Inversa de la Matriz Diagonal

$$D^{-1}=\left(\begin{array}{cccc}\frac {1}{7} & 0 & 0 & 0 \\ 0 & \frac{1}{8} & 0 & 0 \\ 0 & 0 & \frac{1}{4} &0 \\
0 & 0 & 0 &\frac{1}{6} \end{array}\right)$$


### Hallamos L_U

$$L-U=\left(\begin{array}{cccc}\ 0 & 1 & 1 & -2 \\ -1 & 0 & 0 & 2 \\ 1 & 0 & 0 & 1 \\
-2 & 2 & 1 & 0\end{array}\right)$$

### Hallamos:: $D^{-1}(L+U)$

$$D^{-1}(L+U)=\left(\begin{array}{cccc}\ 0 & 1 & 1 & -2 \\ -1 & 0 & 0 & 2 \\ 1 & 0 & 0 & 1 \\
-2 & 2 & 1 & 0\end{array}\right)$$

### Hallamos: $D^{-1} b$

$$D^{-1} b=\left(\begin{array}{c}0 \\ 1 \\ 1 \\ -2\end{array}\right)$$

$X^{k}=D^{-1}(L+\cup) x^{(k)}+D^{-1} b=$

$$
\begin{aligned}
&\left(\begin{array}{c}
-0,1425 x_{2}+0,1429 x_{3}-0,285+x_{4} \\
-0,125 x_{1}+0,25 x_{4} \\
0,25 x_{1}+0,25 x_{4} \\
-0,3333 x_{1}+0,3333 x_{2} + 0,1667 x_{3}
\end{array}\right)+\left(\begin{array}{c}
0,4286 \\
-0,625 \\
1 \\
-0,5
\end{array}\right)\\
\end{aligned}
$$

$x_{1}^{k}=-0,1425 x_{1}+0,1429 x_{3}-0,2857 x_{4}+0,4286$

$x_{2}^{k}=-0,125 x_{1}+0,25 x_{4}-0,625$

$x_{3}^{k}=0,25 x_{1}+0,25 x_{4}+1$

$x_{4}^{k}-0,3333 x_{1}+0,3330 x_{2}+0,1667 x_{3}-0,5$

$x^{(0)}=[0,0,0,0\}$
          




In [21]:
import numpy as np
A=np.array([[7,1,-1,2],[1,8,0,-2],[-1,0,4,-1],[2,-2,-1,6]])
b=np.array([3,-5,4,-3])
k=15
n=A.shape[1]
D=np.eye(n)
D[np.arange(n),np.arange(n)]=A[np.arange(n),np.arange(n)]
LU=D-A
L=np.tril(LU)
U=np.triu(LU)
X=np.zeros(n)
print(" ",0,"Vector Inicial:",X)
for i in range(k):
    D_inv=np.linalg.inv(D)
    X=np.dot(np.dot(D_inv,L+U),X)+np.dot(D_inv,b)
    print(" ",i+1,"El resultado de la interaccion obtenida es:",X.round(decimals=4))
    
    xR = ([1,-1,1,-1])
e = np.zeros(4)
for i in range(4):
    e[i] = (xR[i]-X[i])/xR[i]
    print('\n El error de x',i+1,'es =',100*abs(e[i]),'%')
    
      
    

  0 Vector Inicial: [0. 0. 0. 0.]
  1 El resultado de la interaccion obtenida es: [ 0.4286 -0.625   1.     -0.5   ]
  2 El resultado de la interaccion obtenida es: [ 0.8036 -0.8036  0.9821 -0.6845]
  3 El resultado de la interaccion obtenida es: [ 0.8793 -0.8966  1.0298 -0.872 ]
  4 El resultado de la interaccion obtenida es: [ 0.9529 -0.9529  1.0018 -0.9203]
  5 El resultado de la interaccion obtenida es: [ 0.9708 -0.9742  1.0081 -0.9683]
  6 El resultado de la interaccion obtenida es: [ 0.9884 -0.9884  1.0006 -0.9803]
  7 El resultado de la interaccion obtenida es: [ 0.9928 -0.9936  1.002  -0.9922]
  8 El resultado de la interaccion obtenida es: [ 0.9971 -0.9971  1.0002 -0.9951]
  9 El resultado de la interaccion obtenida es: [ 0.9982 -0.9984  1.0005 -0.9981]
  10 El resultado de la interaccion obtenida es: [ 0.9993 -0.9993  1.     -0.9988]
  11 El resultado de la interaccion obtenida es: [ 0.9996 -0.9996  1.0001 -0.9995]
  12 El resultado de la interaccion obtenida es: [ 0.9998 -0.9

### Método Gauss Seidel ###

In [10]:
import numpy as np
A=np.array([[7,1,-1,2],[1,8,0,-2],[-1,0,4,-1],[2,-2,-1,6]])
b=np.array([3,-5,4,-3])
k=8
n=A.shape[1]
D=np.eye(n) # Matriz de la Identidad
D[np.arange(n),np.arange(n)]=A[np.arange(n),np.arange(n)] # MATRIZ DIAGONAL
LU=D-A
L=np.tril(LU)
U=np.triu(LU)
DL=D-L
X=np.zeros(n)
print(" ",0,"Vector Inicial:",X)
for i in range(k):
    DL_inv=np.linalg.inv(DL)
    X=np.dot(np.dot(DL_inv,U),X)+np.dot(DL_inv,b)
    print(" ",i+1,"El resultado de la interaccion es:",X.round(decimals=4))
    
    xR = ([1,-1,1,-1])
e = np.zeros(4)
for i in range(4):
    e[i] = (xR[i]-X[i])/xR[i]
    print('El error de x',i+1,'es =',100*abs(e[i]),'%')

  0 Vector Inicial: [0. 0. 0. 0.]
  1 El resultado de la interaccion obtenida es: [ 0.4286 -0.6786  1.1071 -0.6845]
  2 El resultado de la interaccion obtenida es: [ 0.8793 -0.906   1.0487 -0.9203]
  3 El resultado de la interaccion obtenida es: [ 0.9708 -0.9764  1.0126 -0.9803]
  4 El resultado de la interaccion obtenida es: [ 0.9928 -0.9942  1.0031 -0.9951]
  5 El resultado de la interaccion obtenida es: [ 0.9982 -0.9986  1.0008 -0.9988]
  6 El resultado de la interaccion obtenida es: [ 0.9996 -0.9996  1.0002 -0.9997]
  7 El resultado de la interaccion obtenida es: [ 0.9999 -0.9999  1.     -0.9999]
  8 El resultado de la interaccion obtenida es: [ 1. -1.  1. -1.]
El error de x 1 es = 0.002663216363818499 %
El error de x 2 es = 0.002157104000255483 %
El error de x 3 es = 0.0011583978638318726 %
El error de x 4 es = 0.0017998397653373743 %


### Método SOR ###

In [11]:
import numpy as np
A=np.array([[7,1,-1,2],[1,8,0,-2],[-1,0,4,-1],[2,-2,-1,6]])
b=np.array([3,-5,4,-3])
k=5
w=1.1
n=A.shape[1]
D=np.eye(n) # Matriz de la Identidad
D[np.arange(n),np.arange(n)]=A[np.arange(n),np.arange(n)] # Matriz Diagonal
LU=D-A
L=np.tril(LU)
U=np.triu(LU)
D_wL=D-w*L
X=np.zeros(n)
print(" ",0,"Vector Inicial:",X)
for i in range(k):
    D_wL_inv=np.linalg.inv(D_wL)
    X=np.dot(np.dot(D_wL_inv,(1-w)*D+w*U),X)+w*np.dot(D_wL_inv,b)
    print(" ",i+1,"El resultado de la interacción es:",X.round(decimals=4))
    
    xR = ([1,-1,1,-1])
e = np.zeros(4)
for i in range(4):
    e[i] = (xR[i]-X[i])/xR[i]
    print('El error de x',i+1,'es =',100*abs(e[i]),'%')

  0 Vector Inicial: [0. 0. 0. 0.]
  1 El resultado de la interacción es: [ 0.4714 -0.7523  1.2296 -0.7733]
  2 El resultado de la interacción es: [ 0.9788 -0.9595  1.0335 -0.9939]
  3 El resultado de la interacción es: [ 0.9991 -1.0022  0.9981 -1.0015]
  4 El resultado de la interacción es: [ 1.0006 -1.0003  1.     -1.0002]
  5 El resultado de la interacción es: [ 1. -1.  1. -1.]
El error de x 1 es = 0.0029419032669952827 %
El error de x 2 es = 0.002681983306263014 %
El error de x 3 es = 0.0036134375151153364 %
El error de x 4 es = 0.0009534752473339125 %


### Ejemplo
#### Determine la norma Frobenius de la sigueinte matriz:
$$A=\left(\begin{array}{cccc}1&2&5&6\\6&4&0&0\\5&-8&3&5\\8&6&4&5\end{array}\right)$$

#### Respuesta
$$\parallel{A}\parallel_{F}=\sqrt{(1)^2+(2)^2+(5)^2+(6)^2+(6)^2+(4)^2+(0)^2+(0)^2+(5)^2+(-8)^2+(3)^2+(5)^2+(8)^2+(6)^2+(4)^2+(5)^2}$$
$$\parallel{A}\parallel_{F}=\sqrt{382}= 19.544820 $$

In [27]:
import numpy as np
from math import sqrt

### Matriz (A):
A=np.array([[1,2,5,6],[6,4,0,0],[5,-8,3,5],[8,6,4,5]])
m=A.shape[0] # Numero Filas
n=A.shape[1] # Numero Columnas
sum_raiz=0
for i in range(m):
    for j in range(n):
            sum_raiz+=pow(A[i][j],2)
    Res=sqrt(sum_raiz)

print("Frobenius es : ",Res)


Frobenius es :  19.544820285692065
